version: "3.7"
services: 
  web:
    build: .
    volumes: 
      - .:/var/www/html
      - ./httpd/sites-enabled:/etc/apache2/sites-enabled
    working_dir: "/var/www/html"
    ports: 
      - 80:80
      - 443:443
    networks: 
      - nanophp
  mariadb:
    image: "mariadb"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
      - nanophp
  adminer:
    image: "adminer"
    ports:
      - 8888:8080
    links: 
      - mariadb
    networks:
      - nanophp
networks: 
  nanophp:
