version: "3.7"
services: 
  web:
    build: .
    ports: 
      - 80:80
    volumes: 
      - .:/var/www/html
    working_dir: "/var/www/html"
    command: "php serve.php"
    networks: 
      - nanophp
  mariadb:
    image: "mariadb"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
      - nanophp
  adminer:
    image: "adminer"
    ports:
      - 8080:8080
    links: 
      - mariadb
    networks:
      - nanophp
networks: 
  nanophp:
